
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//Home Type
export const LIST_HOME = 'LIST_HOME';
export const HOME_LOADING = 'HOME_LOADING';
export const HOME_STOPLOADING = 'HOME_STOPLOADING';
//Blog Type
export const LIST_BLOG = 'LIST_BLOG';
export const BLOG_LOADING = 'BLOG_LOADING';
export const BLOG_STOPLOADING = 'BLOG_STOPLOADING';

//PRODUCT Type
export const LIST_PRODUCT = 'LIST_PRODUCT';
export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const PRODUCT_STOPLOADING = 'PRODUCT_STOPLOADING';

//CART Type
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const LOAD_CART = 'LOAD_CART';

//SHIPPING TYPE
export const LIST_SHIPPING = 'LIST_SHIPPING';
export const SHIPPING_LOADING = 'SHIPPING_LOADING';
export const SHIPPING_STOPLOADING = 'SHIPPING_STOPLOADING';

//Wishlist Type
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS';
export const REMOVE_FROM_WISHLIST_SUCCESS = 'REMOVE_FROM_WISHLIST_SUCCESS';
export const LOAD_WISHLIST = 'LOAD_WISHLIST';

//Product Slider Type
export const GET_PRODUCT_SLIDER = 'GET_PRODUCT_SLIDER';






// Get Product Items Type
export const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

// Get Product Attribute Type
export const GET_PRODUCT_ATTRIBUTE_LOADING = "GET_PRODUCT_ATTRIBUTE_LOADING";
export const GET_PRODUCT_ATTRIBUTE_SUCCESS = "GET_PRODUCT_ATTRIBUTE_SUCCESS";
export const GET_PRODUCT_ATTRIBUTE_FAIL = "GET_PRODUCT_ATTRIBUTE_FAIL";
